# Generated by Django 6.1.1 on 2026-09-28 03:09

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_restaurantstaff'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='service_charge_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='restaurant_tax_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='restaurant',
            constraint=models.CheckConstraint(condition=models.Q(('service_charge_rate__gte', 0), ('service_charge_rate__lte', 100)), name='restaurant_service_charge_rate_range'),
        ),
    ]
