# Generated by Django 6.1.1 on 2026-09-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
