# Generated by Django 6.1.1 on 2026-09-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='quantity_on_hand',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
