# Generated by Django 6.1.1 on 2026-09-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitemingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemingredient',
            name='quantity_required',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
